clube/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # index
    path('', Index, name='index'),

    # urls do associado

    path('associados/', AssociadoListView.as_view(), name='associado_list'),
    path('associados/<int:pk>/', AssociadoDetailView.as_view(), name='associado_detail'),
    path('associados/cadastrar/', AssociadoCreateView.as_view(), name='associado_cadastrar'),
    path('associados/<int:pk>/editar/', AssociadoUpdateView.as_view(), name='associado_edit'),
    path('associados/<int:pk>/excluir/', AssociadoDeleteView.as_view(), name='associado_delete'),

    # urls do dependente

    path('associados/<int:associado_id>/dependentes/<int:pk>/', DependenteDetailView.as_view(), name='dependente_detail'),
    path('associados/<int:associado_id>/dependentes/cadastrar/', DependenteCreateView.as_view(), name='dependente_cadastrar'),
    path('associados/<int:associado_id>/dependentes/<int:pk>/editar/', DependenteUpdateView.as_view(), name='dependente_edit'),
    path('dependentes/<int:pk>/excluir/', DependenteDeleteView.as_view(), name='dependente_delete'),

    # urls do espaco

    path('espacos/', EspacoListView.as_view(), name='espaco_list'),
    path('espacos/cadastrar/', EspacoCreateView.as_view(), name='espaco_cadastrar'),
    path('espacos/<int:pk>/editar/', EspacoUpdateView.as_view(), name='espaco_edit'),
    path('espacos/<int:pk>/excluir/', EspacoDeleteView.as_view(), name='espaco_delete'),

    # urls do fornecedor

    path('fornecedores/', FornecedorListView.as_view(), name='fornecedor_list'),
    path('fornecedores/cadastrar/', FornecedorCreateView.as_view(), name='fornecedor_cadastrar'),
    path('fornecedores/<int:pk>/', FornecedorDetailView.as_view(), name='fornecedor_detail'),
    path('fornecedores/<int:pk>/editar/', FornecedorUpdateView.as_view(), name='fornecedor_edit'),
    path('fornecedores/<int:pk>/excluir/', FornecedorDeleteView.as_view(), name='fornecedor_delete'),

    # urls da agenda

    path('agenda/', AgendaListView.as_view(), name='agenda_list'),
    path('convidados/cadastrar/', ConvidadoCreateView.as_view(), name='convidado_cadastrar'),
    path('agenda/cadastrar/', agenda_cadastrar, name='agenda_cadastrar'),
    path('agenda/<int:agenda_id>/add_convidados/', add_convidados, name='add_convidados'),
    path('agenda/<int:pk>/edit/', AgendaUpdateView.as_view(), name='agenda_edit'),
    path('agenda/<int:agenda_id>/edit_convidados/', edit_convidados, name='edit_convidados'),
    path('agenda/<int:pk>/', AgendaDetailView.as_view(), name='agenda_detail'),
    path('agenda/<int:pk>/excluir/', AgendaDeleteView.as_view(), name='agenda_delete'),

    # urls de convidados

    path('convidados/', ConvidadoListView.as_view(), name='convidado_list'),
    path('convidados/<int:pk>/excluir/', ConvidadoDeleteView.as_view(), name='convidado_delete'),
    path('convidados/<int:pk>/editar/', ConvidadoUpdateView.as_view(), name='convidado_edit'),
    # Repita o mesmo padrão para outros modelos
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clube.urls')),
]

clube/models.py
from django.db import models

# Create your models here.

associacao = [
        ('fundador', 'Sócio Fundador'),
        ('proprietario', 'Sócio Proprietário'),
        ('cotista', 'Sócio Cotista'),
        ('voluntario', 'Sócio Voluntário')
    ]

uf = [
    ('AC', 'Acre'),
        ('AL', 'Alagoas'),
        ('AP', 'Amapá'),
        ('AM', 'Amazonas'),
        ('BA', 'Bahia'),
        ('CE', 'Ceará'),
        ('DF', 'Distrito Federal'),
        ('ES', 'Espírito Santo'),
        ('GO', 'Goiás'),
        ('MA', 'Maranhão'),
        ('MT', 'Mato Grosso'),
        ('MS', 'Mato Grosso do Sul'),
        ('MG', 'Minas Gerais'),
        ('PA', 'Pará'),
        ('PB', 'Paraíba'),
        ('PR', 'Paraná'),
        ('PE', 'Pernambuco'),
        ('PI', 'Piauí'),
        ('RJ', 'Rio de Janeiro'),
        ('RN', 'Rio Grande do Norte'),
        ('RS', 'Rio Grande do Sul'),
        ('RO', 'Rondônia'),
        ('RR', 'Roraima'),
        ('SC', 'Santa Catarina'),
        ('SP', 'São Paulo'),
        ('SE', 'Sergipe'),
        ('TO', 'Tocantins'),
]

class Associado(models.Model):
    nome = models.CharField(max_length=100)
    endereco = models.CharField(max_length=200)
    bairro = models.CharField(max_length=50)
    cep = models.CharField(max_length=10)
    complemento = models.CharField(max_length=100, blank=True, null=True)
    cidade = models.CharField(max_length=100)
    uf = models.CharField(max_length=2, choices=uf)
    telefone = models.CharField(max_length=15)
    celular = models.CharField(max_length=15)
    email = models.EmailField()
    facebook = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    cpf = models.CharField(max_length=14)
    rg = models.CharField(max_length=20)
    data_nascimento = models.DateField()
    tipo_associacao = models.CharField(max_length=50, choices=associacao)
    
    def __str__(self):
        return self.nome

class Dependente(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14)
    rg = models.CharField(max_length=20)
    data_nascimento = models.DateField()
    tipo_vinculo = models.CharField(max_length=50)
    socio_titular = models.ForeignKey(Associado, on_delete=models.CASCADE, related_name='dependentes')

class EspacoLocavel(models.Model):
    nome = models.CharField(max_length=100)
    tamanho = models.IntegerField()
    capacidade_pessoas = models.IntegerField()
    data_construcao_aquisicao = models.DateField()
    locavel = models.BooleanField(default=True)

    def __str__(self):
        return self.nome

class Fornecedor(models.Model):
    nome_razao_social = models.CharField(max_length=100)
    endereco = models.CharField(max_length=200)
    bairro = models.CharField(max_length=50)
    numero = models.CharField(max_length=10)
    cep = models.CharField(max_length=10)
    cidade = models.CharField(max_length=100)
    uf = models.CharField(max_length=2, choices=uf)
    telefone = models.CharField(max_length=15)
    celular = models.CharField(max_length=15)
    email = models.EmailField()
    facebook = models.URLField(blank=True, null=True)
    instagram = models.URLField(blank=True, null=True)
    contato = models.CharField(max_length=100)

class Convidado(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14)
    rg = models.CharField(max_length=20)
    celular = models.CharField(max_length=15)
    telefone = models.CharField(max_length=15)
    email = models.EmailField()

class Agenda(models.Model):
    espaco_locavel = models.ForeignKey(EspacoLocavel, on_delete=models.CASCADE)
    valor_locacao = models.DecimalField(max_digits=10, decimal_places=2)
    data_hora_inicio = models.DateTimeField()
    data_hora_fim = models.DateTimeField()
    responsavel_locacao = models.ForeignKey(Associado, on_delete=models.CASCADE)
    convidados = models.ManyToManyField(Convidado, blank=True)

    def clean(self):
        # Check for overlapping events for the same EspacoLocavel
        overlapping_events = Agenda.objects.filter(
            espaco_locavel=self.espaco_locavel,
            data_hora_inicio__lt=self.data_hora_fim,
            data_hora_fim__gt=self.data_hora_inicio,
        ).exclude(pk=self.pk)

        if overlapping_events.exists():
            raise ValidationError('Este horário já está em uso por outro evento neste local')
        validate_locavel(self.espaco_locavel)


from django.core.exceptions import ValidationError

def validate_locavel(value):
    if not value.locavel:
        raise ValidationError('Este espaço não é locável.')

clube/forms.py
from django import forms
from .models import *

class AssociadoForm(forms.ModelForm):
    class Meta:
        model = Associado
        fields = '__all__'
        widgets = {
            'data_nascimento': forms.DateInput(attrs={'type': 'date'}),
        }  

class DependenteForm(forms.ModelForm):
    class Meta:
        model = Dependente
        exclude = ['socio_titular']
        widgets = {
                'data_nascimento': forms.DateInput(attrs={'type': 'date'}),
            }  

class EspacoForm(forms.ModelForm):
    class Meta:
        model = EspacoLocavel
        fields = '__all__'
        widgets = {
                'data_construcao_aquisicao': forms.DateInput(attrs={'type': 'date'}),
            }  

class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = '__all__'

class ConvidadoForm(forms.ModelForm):
    class Meta:
        model = Convidado
        fields = '__all__'

class AgendaForm(forms.ModelForm):
    class Meta:
        model = Agenda
        exclude = ['convidados']
        widgets = {
            'data_hora_inicio': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'data_hora_fim': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

clube/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views import View
from .models import Associado, Dependente, EspacoLocavel, Fornecedor, Convidado, Agenda
from .forms import *
from django.urls import reverse_lazy

# views do associado

def Index(request):
    return render(request, 'index.html')

class AssociadoListView(ListView):
    model = Associado
    template_name = 'associado/associado_list.html'

class AssociadoDetailView(DetailView):
    model = Associado
    template_name = 'associado/associado_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dependentes'] = self.object.dependentes.all()
        return context

class AssociadoCreateView(CreateView):
    model = Associado
    form_class = AssociadoForm
    template_name = 'associado/associado_form.html'
    success_url = '/associados/'

class AssociadoUpdateView(UpdateView):
    model = Associado
    form_class = AssociadoForm
    template_name = 'associado/associado_edit.html'

    def get_success_url(self):
        return reverse_lazy('associado_detail', kwargs={'pk': self.object.pk})
    
class AssociadoDeleteView(DeleteView):
    model = Associado
    success_url = reverse_lazy('associado_list')

# views do dependente

class DependenteDetailView(DetailView):
    model = Dependente
    template_name = 'dependente/dependente_detail.html'

class DependenteCreateView(CreateView):
    model = Dependente
    form_class = DependenteForm
    template_name = 'dependente/dependente_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['associado_id'] = self.kwargs['associado_id']
        return context

    def form_valid(self, form):
        form.instance.socio_titular_id = self.kwargs['associado_id']
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('associado_detail', kwargs={'pk': self.kwargs['associado_id']})
    
class DependenteUpdateView(UpdateView):
    model = Dependente
    form_class = DependenteForm
    template_name = 'dependente/dependente_edit.html'

    def get_success_url(self):
        return reverse_lazy('dependente_detail', kwargs={'pk': self.object.pk})
    
class DependenteDeleteView(DeleteView):
    model = Dependente

    def get_success_url(self):
        return reverse_lazy('associado_detail', kwargs={'pk': self.object.socio_titular.pk})

    
    
# views do espaco locavel

class EspacoListView(ListView):
    model = EspacoLocavel
    template_name = 'espaco/espaco_list.html'

class EspacoCreateView(CreateView):
    model = EspacoLocavel
    form_class = EspacoForm
    template_name = 'espaco/espaco_form.html'
    success_url = reverse_lazy('espaco_list')

class EspacoUpdateView(UpdateView):
    model = EspacoLocavel
    form_class = EspacoForm
    template_name = 'espaco/espaco_edit.html'

    def get_success_url(self):
        return reverse_lazy('espaco_list')
    
class EspacoDeleteView(DeleteView):
    model = EspacoLocavel
    success_url = reverse_lazy('espaco_list')

# views do fornecedor

class FornecedorListView(ListView):
    model = Fornecedor
    template_name = 'fornecedor/fornecedor_list.html'

class FornecedorDetailView(DetailView):
    model = Fornecedor
    template_name = 'fornecedor/fornecedor_detail.html'

class FornecedorCreateView(CreateView):
    model = Fornecedor
    form_class = FornecedorForm
    template_name = 'fornecedor/fornecedor_form.html'
    success_url = reverse_lazy('fornecedor_list')

class FornecedorUpdateView(UpdateView):
    model = Fornecedor
    form_class = FornecedorForm
    template_name = 'fornecedor/fornecedor_edit.html'

    def get_success_url(self):
        return reverse_lazy('fornecedor_detail', kwargs={'pk': self.object.pk})

class FornecedorDeleteView(DeleteView):
    model = Fornecedor
    success_url = reverse_lazy('fornecedor_list')
    

#views do convidado

class ConvidadoCreateView(CreateView):
    model = Convidado
    form_class = ConvidadoForm
    template_name = 'convidado/convidado_form.html'
    def get_success_url(self):
        return reverse_lazy('convidado_cadastrar')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existing_convidados'] = Convidado.objects.all()
        return context
    
class ConvidadoListView(ListView):
    model = Convidado
    template_name = 'convidado/convidado_list.html'

class ConvidadoUpdateView(UpdateView):
    model = Convidado
    form_class = ConvidadoForm
    template_name = 'convidado/convidado_edit.html'

    def get_success_url(self):
        return reverse_lazy('convidado_list')
    
class ConvidadoDeleteView(DeleteView):
    model = Convidado
    success_url = reverse_lazy('convidado_list')

#views da agenda

class AgendaListView(ListView):
    model = Agenda
    template_name = 'agenda/agenda_list.html'

class AgendaDetailView(DetailView):
    model = Agenda
    template_name = 'agenda/agenda_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['convidados'] = self.object.convidados.all()
        return context

class AgendaUpdateView(UpdateView):
    model = Agenda
    form_class = AgendaForm
    template_name = 'agenda/agenda_edit.html'
    success_url = reverse_lazy('agenda_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existing_convidados'] = Convidado.objects.all()
        return context
    
class AgendaDeleteView(DeleteView):
    model = Agenda
    success_url = reverse_lazy('agenda_list')

def agenda_cadastrar(request):
    if request.method == 'POST':
        agenda_form = AgendaForm(request.POST)
        if agenda_form.is_valid():
            agenda = agenda_form.save(commit=False)
            agenda.save()
            return redirect('add_convidados', agenda_id=agenda.id)
    else:
        agenda_form = AgendaForm()

    return render(request, 'agenda/agenda_form.html', {'agenda_form': agenda_form})

def add_convidados(request, agenda_id):
    agenda = Agenda.objects.get(id=agenda_id)

    if request.method == 'POST':
        # Processar form com convidados selecionados
        selected_convidados = request.POST.getlist('convidados')
        agenda.convidados.set(selected_convidados)
        return redirect('agenda_list')  

    # Fetch dos convidados existentes para seleção
    existing_convidados = Convidado.objects.all()
    convidado_form = ConvidadoForm()

    return render(request, 'agenda/agenda_convidados.html', {'convidado_form': convidado_form, 'agenda': agenda, 'existing_convidados': existing_convidados})


def edit_convidados(request, agenda_id):
    agenda = Agenda.objects.get(id=agenda_id)

    if request.method == 'POST':
        selected_convidados = request.POST.getlist('convidados')
        agenda.convidados.set(selected_convidados)
        return redirect('agenda_list')

    existing_convidados = Convidado.objects.all()
    convidado_form = ConvidadoForm()

    return render(request, 'agenda/agenda_edit_convidados.html', {'convidado_form': convidado_form, 'agenda': agenda, 'existing_convidados': existing_convidados})

clube/templates/associado/associado_detail.html
<!-- associado_detail.html -->
{% load crispy_forms_tags %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div style="padding-bottom: 15px;" class="container">
        <h2>Detalhes do Associado</h2>
        <p>Nome: {{ object.nome }}</p>
        <p>Endereço: {{ object.endereco }}</p>
        <p>Bairro: {{ object.bairro }}</p>
        <p>CEP: {{ object.cep }}</p>
        <p>Complemento: {{ object.complemento }}</p>
        <p>Cidade: {{ object.cidade }}</p>
        <p>UF: {{ object.uf }}</p>
        <p>Telefone: {{ object.telefone }}</p>
        <p>Celular: {{ object.celular }}</p>
        <p>Email: {{ object.email }}</p>
        <p>Facebook: {% if object.facebook %}<a href="{{ object.facebook }}" target="_blank">{{ object.facebook }}</a>{% endif %}</p>
        <p>Instagram: {% if object.instagram %}<a href="{{ object.instagram }}" target="_blank">{{ object.instagram }}</a>{% endif %}</p>
        <p>CPF: {{ object.cpf }}</p>
        <p>RG: {{ object.rg }}</p>
        <p>Data de Nascimento: {{ object.data_nascimento }}</p>
        <p>Tipo de Associação: {{ object.tipo_associacao }}</p>

        {% if dependentes %}
            <h3>Dependentes:</h3>
            <ul>
                {% for dependente in dependentes %}
                    <li>{{ dependente.nome }} - {{ dependente.tipo_vinculo }} <a href="{% url 'dependente_detail' associado_id=dependente.socio_titular.pk pk=dependente.pk %}">Detalhes</a></li>
                    <!-- Adicione outros campos conforme necessário -->
                {% endfor %}
            </ul>
        {% else %}
            <p>Este membro não tem dependentes.</p>
        {% endif %}
        <a class="btn btn-secondary" href="{% url 'associado_list' %}">Voltar</a>
        <a class="btn btn-primary" href="{% url 'dependente_cadastrar' associado_id=object.id %}">Adicionar Dependente</a>
        <a class="btn btn-primary" href="{% url 'associado_edit' pk=object.pk %}">Editar</a>
        <button style="float: right;" type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">
            Excluir Associado
          </button>
          <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="confirmDeleteModalLabel">Confirmação de Exclusão</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <p>Tem certeza de que deseja excluir este associado?</p>
                </div>
                <div class="modal-footer">
                    <form method="post" action="{% url 'associado_delete' pk=object.pk %}">
                        {% csrf_token %}
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
                    </form>
                </div>
              </div>
            </div>
          </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

clube/templates/associado/associado_edit.html
{% load crispy_forms_tags %}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div style="padding-bottom: 15px;" class="container">
        <h2>Editar Associado</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Salvar Alterações</button>
        </form>
        <a class="btn btn-secondary" href="{% url 'associado_detail' pk=object.pk %}">Cancelar</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

clube/templates/associado/associado_form.html
{% load crispy_forms_tags %}
<!-- associados/associado_form.html -->
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <!--
    <nav class="navbar bg-dark mb-4" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="">Associados</a>
        </div>
    </nav>-->

    
    <main class="container">
        <br>
        <h1>Cadastrar Associado</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Cadastrar</button>
            <a class="btn btn-secondary" href="{% url 'associado_list' %}">Cancelar</a>
        </form>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

clube/templates/associado/associado_list.html
<!-- associado_list.html -->
{% load crispy_forms_tags %}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

    <br>
    <div class="container">
        <a class="btn btn-primary" href="{% url 'associado_cadastrar' %}">Cadastrar Associado</a>
        <a style="float: right;" class="btn btn-secondary" href="{% url 'index' %}">Menu</a>
        <br><br>
        <h2>Lista de Associados</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Tipo de Associação</th>
                <th></th>
                <!-- Add more columns as needed -->
              </tr>
            </thead>
            <tbody>
              {% for associado in object_list %}
                <tr>
                  <td>{{ associado.nome }}</td>
                  <td>{{ associado.get_tipo_associacao_display }}</td>
                  <!-- Add more columns as needed -->
                  <td><a href="{% url 'associado_detail' pk=associado.pk %}">Detalhes</a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>